// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reminder.proto

package reminder

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/arkadyb/go-proto-validators"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	time "time"
	github_com_golang_protobuf_ptypes "github.com/golang/protobuf/ptypes"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ScheduleReminderRequest) Validate() error {
	if nil == this.When {
		return fmt.Errorf("field When cant be nil")
	}
	tsWhen, err := github_com_golang_protobuf_ptypes.Timestamp(this.When)
	if err != nil {
		return fmt.Errorf("faield to convert When to Timestamp")
	}
	if !tsWhen.After(time.Now()) {
		return fmt.Errorf("must be future timestamp")
	}
	return nil
}
func (this *ScheduleReminderResponse) Validate() error {
	return nil
}
